title: "Élie Saikali"
author: "Élie Saikali"
description: "Research scientist at CEA, Lecturer at LeCNAM"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  #- {file: "home.md", title: "Home"}
  - {file: "publi.md", title: "Publications"}
  - {file: "links.md", title: "Useful Links"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:elie.saikali@cea.fr"}
  - {title: Github, icon: github, url: "https://github.com/eliesaikali"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/%C3%A9lie-saikali-aa3b3826/"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Elie-Saikali"}
  - {title: GoogleScholar, icon: google, url: "https://scholar.google.fr/citations?user=y7KK9cIAAAAJ&hl=en"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
